# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datacolreq',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datasetname', models.CharField(max_length=100)),
                ('srcport', models.CharField(max_length=10)),
                ('dstport', models.CharField(max_length=10)),
                ('srcip', models.CharField(max_length=100)),
                ('dstip', models.CharField(max_length=100)),
                ('pro', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=10)),
                ('num', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dataset',
            fields=[
                ('datasetid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('datasetname', models.CharField(default=b' ', max_length=50)),
                ('username', models.CharField(default=b' ', max_length=50)),
                ('status', models.CharField(default=b' ', max_length=20)),
                ('category', models.CharField(default=b' ', max_length=50)),
                ('source', models.CharField(default=b' ', max_length=50)),
                ('anonymization', models.CharField(default=b' ', max_length=20)),
                ('releasedate', models.CharField(default=b' ', max_length=20)),
            ],
        ),
    ]
