# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('UserGroup', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Url', models.URLField()),
            ],
        ),
    ]
